spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: plataforma-database-pool
      auto-commit: false
      connection-timeout: 30000
    url: "jdbc:postgresql://0.0.0.0:5432/bookhive"
    username: postgres
    password: 123
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true