spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: plataforma-database-pool
      auto-commit: false
      connection-timeout: 30000
    url: jdbc:postgresql://dpg-cte37dtds78s739i357g-a.oregon-postgres.render.com:5432/bookhivedb_q7zr
    username: bookhivedb_q7zr_user
    password: sRb74QR524qoZ548Gq1Ofx5Z5qQGDzgg
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always

